services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    expose:
      - 8181
    volumes:
      - ${DOCKER_DATA_DIR}/tautulli:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ:-UTC}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`${TAUTULLI_HOSTNAME?}`)"
      - "traefik.http.routers.tautulli.entrypoints=websecure"
      - "traefik.http.routers.tautulli.tls.certresolver=letsencrypt"
      - "flame.type=app"
      - "flame.name=Tautulli"
      - "flame.url=https://${TAUTULLI_HOSTNAME}"
    profiles:
      - all
      - tautulli
      - debrid_media_server
