services:
  torbox-media-center:
      image: anonymoussystems/torbox-media-center:main
      container_name: torbox-media-center
      stdin_open: true
      tty: true
      restart: unless-stopped
      volumes:
            - ${DOCKER_DATA_DIR}/torbox:/torbox
      environment:
            - TORBOX_API_KEY=${TORBOX_API_KEY}
            - MOUNT_METHOD=${TORBOX_MOUNT_METHOD}
            - MOUNT_PATH=/torbox
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.torboxmedia.rule=Host(`${TORBOX_MEDIA_CENTER_HOSTNAME?}`)"
        - "traefik.http.routers.torboxmedia.entrypoints=websecure"
        - "traefik.http.routers.torboxmedia.tls.certresolver=letsencrypt"
      profiles:
        - debrid_media_server
        - all