services:
  torbox-manager:
    image: charleeislegend/torbox-manager:latest
    container_name: torbox-manager
    expose:
      - 3000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tbm.rule=Host(`${TBM_HOSTNAME?}`)"
      - "traefik.http.routers.tbm.entrypoints=websecure"
      - "traefik.http.routers.tbm.tls.certresolver=myresolver"
      - "traefik.http.routers.tbm.middlewares=authelia@docker"
    profiles:
      - torbox-manager
      - all
